### PR TITLE
Include Default Resolver Class

### PR DESCRIPTION
**Pull request by maikvortx**
## Proposed Changes

1. Inclusion of the Default Resolver class
2. Inclusion of the documentation to readme

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request
- [x] Remember to check if code coverage decrease, if so, please implement the necessary tests

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by maikvortx** [comment]
Hello @dalssoft!
I updated the documentation with your suggestions.

**Review by dalssoft — APPROVED** [review]

**Comment by dalssoft** [comment]
@maikvortx next step would be to update to-do list.

**Comment by maikvortx** [comment]
Hey @dalssoft!

Will the new version of the herbs2gql npm package be released automatically after the CI is executed?

**Comment by dalssoft** [comment]
@maikmb not really but I've just published the new version.

**Comment by maikvortx** [comment]
Thanks! I will update TodoList!

**Pull request merged**
